version: "3.9"

services:
  db:
    image: postgres:15
    env_file: .env
    environment:
      POSTGRES_USER: ${DB_USER_TEST}
      POSTGRES_PASSWORD: ${DB_PASS_TEST}
      POSTGRES_DB: ${DB_NAME_TEST}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      tasks-api-backend:
  
  api:
    build: .
    env_file: .env
    depends_on:
      - db
    ports:
      - "8000:8000"
    networks:
      tasks-api-backend:
      tasks-api-frontend:

volumes:
  postgres_data:

networks:
  tasks-api-backend:
  tasks-api-frontend: